languaje: java
jdk: 
- openjdk8
- openjdk10
services:
- mysql
install:
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
before_install:
- chmod +x mvnw 
script: mvn clean compile package 
before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('sasa') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
on:
    branch: master



