dist: precise
languaje: java
jdk: 
- openjdk10
services:
- postgresql
install:
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
before_install:
- chmod +x mvnw 
 - psql -c 'create database db02fbkv8ge7t4;' -U postgres

on:
    branch: master



